apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubservice
  template:
    metadata:
      labels:
        app: hubservice
    spec:
      containers:
      - name: hubservice
        image: johannesdigdir/hub_service:b8549e81a279964ba120be05ae109f3c88ad2ec8
        ports:
        - containerPort: 5000