apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubservice
  template:
    metadata:
      labels:
        app: hubservice
    spec:
      containers:
      - name: hubservice
        image: johannesdigdir/hub_service:3ccb6950ba0aeb1150b215594e0f99d766eb6643
        ports:
        - containerPort: 5000