apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubservice
  template:
    metadata:
      labels:
        app: hubservice
    spec:
      containers:
      - name: hubservice
        image: johannesdigdir/hub_service:4480bc2faf726a60440ee01520485008113aa7f6
        ports:
        - containerPort: 5000