apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubservice
  template:
    metadata:
      labels:
        app: hubservice
    spec:
      containers:
      - name: hubservice
        image: johannesdigdir/hub_service:4a9ecaeea441fbf377a7190c429d4c1d47289c34
        ports:
        - containerPort: 5000