apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubservice
  template:
    metadata:
      labels:
        app: hubservice
    spec:
      containers:
      - name: hubservice
        image: johannesdigdir/hub_service:12cfc2e0f06523321f7ebd265d45fea75dc1f33c
        ports:
        - containerPort: 5000