hostname_fregservice="http://fregservice-svc"
hostname_skattservice="http://skatteservice-svc"
hostname_evaluatorservice="http://evaluatorservice-svc"
hostname_exposedataservice="http://"
port_fregservice=":5000"
port_skattservice=":5000"
port_evaluatorservice=":5000"
port_exposedataservice=":5000"
